development:
  adapter: postgresql
  encoding: unicode
  database: stripe_subscription
  host: localhost
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
